# Generated by Django 2.0.3 on 2020-03-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='upload/21.jpg', upload_to='upload', verbose_name='图片'),
        ),
    ]
